version: '3'
services:
  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    networks:
      - express-mongo
      - react-express
    expose:
      - 3001
    ports:
      - 3001:3001

  mongo:
    restart: always
    image: mongo:latest
    volumes:
      - ./data:/data/db
    networks:
      - express-mongo
    expose:
      - 27017
    ports:
      - 27017:27017

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks:
      - react-express
    depends_on:
      - backend

networks:
  express-mongo:
  react-express:
