version: '3'
services:
  frontend:
    container_name: frontend
    image: laerciomlb/restaurant-frontend:latest
    ports:
      - "3000:3000"
    networks:
      - application

  backend:
    container_name: backend
    image: laerciomlb/restaurant-backend:latest
    ports:
      - "3001:3001"
    networks:
      - application

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - application

networks:
  application:
    driver: bridge
