apiVersion: v1
kind: Pod
metadata:
  name: restaurant-web
spec:
  containers:
    - name: frontend
      image: 810527781258.dkr.ecr.us-east-1.amazonaws.com/restaurant-frontend
      ports:
        - containerPort: 3000 

    - name: backend
      image: 810527781258.dkr.ecr.us-east-1.amazonaws.com/restaurant-backend:latest
      ports:
        - containerPort: 3001

    - name: mongo
      image: mongo:latest
      ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-loadbalancer
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
