version: '3'
services:
  frontend:
    container_name: frontend
    image: 829810062801.dkr.ecr.us-east-1.amazonaws.com/restaurant-frontend
    ports:
      - "3000:3000"
    networks:
      - application

  backend:
    container_name: backend
    image: 829810062801.dkr.ecr.us-east-1.amazonaws.com/restaurant-backend
    ports:
      - "3001:3001"
    networks:
      - application

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - application

networks:
  application:
    driver: bridge
