apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f /mnt/c/Users/lbubi/Documents/GitHub/restaurant/compose.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f /mnt/c/Users/lbubi/Documents/GitHub/restaurant/compose.yaml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/restaurant-application: "true"
        io.kompose.service: frontend
    spec:
      containers:
        - image: 810527781258.dkr.ecr.us-east-1.amazonaws.com/restaurant-frontend
          name: frontend
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
            - containerPort: 59214 
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
