name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Setup Node.js 18
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Instalar dependências do backend
      working-directory: ./backend
      run: npm install

    - name: Executar testes do backend
      working-directory: ./backend
      run: npm run test

  frontend:
    runs-on: ubuntu-latest
    needs: backend

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Instalar dependências do frontend
      working-directory: ./frontend
      run: npm install
  build_backend_docker_image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Login no Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build da imagem Docker do backend
      working-directory: ./backend
      run: |
        docker build -t your-username/backend:latest .
        docker push your-username/backend:latest

  build_docker_images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Build da imagem Docker do frontend
      working-directory: ./frontend
      run: |
        docker build -t 810527781258.dkr.ecr.us-east-1.amazonaws.com/restaurant-frontend:latest .

    - name: Build da imagem Docker do backend
      working-directory: ./backend
      run: |
        docker build -t 810527781258.dkr.ecr.us-east-1.amazonaws.com/restaurant-backend:latest .  



      
