name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Setup Node.js 18
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Instalar dependências do backend
      working-directory: ./backend
      run: npm install

    - name: Executar testes do backend
      working-directory: ./backend
      run: npm run test

  frontend:
    runs-on: ubuntu-latest
    needs: backend

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Instalar dependências do frontend
      working-directory: ./frontend
      run: npm install

  build_docker_images:
    runs-on: ubuntu-latest
    needs: frontend

    steps:
    - name: Checkout código
      uses: actions/checkout@v2
      
    - name: Configure AWS credentials for kubectl
      env:
        AWS_ACCESS_KEY_ID: ASIA3ZNZYOGFIDBGTFU7
        AWS_SECRET_ACCESS_KEY: JTW8qGelBsaIsCH+L8YKxGVpsgwjgPu/fq9aKtsY
        AWS_SESSION_TOKEN: FwoGZXIvYXdzEJX//////////wEaDJv7TayThQFRejYrYyLLAbmA3XWK7NvTb8EkZ3tzuoQvOzNAhgdl+YIqA693i07hdOjwMYPXjL3zaxDEFTzGi8wTRGGHs+/Wy1rZSe4/1QTtqU6Y8lsu2SHwEM5Izjb+KEEqX7KlS/kYjRcpoXCpnc5+Yn+y68uGtfd8n7zl73DFeB285zY4q4Ss2de2eZmF61zIIDYZeGIXDHJ4NDbg+tPvdjlHkJ4vbxt7BDJG4VpS1L8K5BvmCTvJw+0Qilvm2GPPbbIOL0/eI8Y8w+6o9I2f47wih8ypRqA0KKDH9akGMi0f/ZKe4DxN7jA8MATPL5jeQ/jF4tpGhY7RKbphjpnAY85POb4g5pQX5n96Qt0=
        AWS_REGION: us-east-1
      run: aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID && aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY && aws configure set aws_session_token $AWS_SESSION_TOKEN && aws configure set region $AWS_REGION
    
    - name: Configure AWS credentials for kubectl
      env:
        AWS_REGION: us-east-1
        AWS_USER_ECR: 810527781258.dkr.ecr.us-east-1.amazonaws.com
        
      run: aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_USER_ECR
    
    - name: Build e Push da imagem Docker do frontend
      working-directory: ./frontend
      run: |
        docker build -t restaurant-frontend . &&
        docker tag restaurant-frontend:latest 810527781258.dkr.ecr.us-east-1.amazonaws.com/restaurant-frontend:latest &&
        docker push 810527781258.dkr.ecr.us-east-1.amazonaws.com/restaurant-frontend:latest

    - name: Build e Push da imagem Docker do backend
      working-directory: ./backend
      run: |
        docker build -t restaurant-backend . &&
        docker tag restaurant-backend:latest 810527781258.dkr.ecr.us-east-1.amazonaws.com/restaurant-backend:latest &&
        docker push 810527781258.dkr.ecr.us-east-1.amazonaws.com/restaurant-backend:latest
    
    - name: Deploy kubernetes
      working-directory: ./
      run: |
        aws eks update-kubeconfig --name aplication-web &&
        kubectl apply -f k8s/
    


      
