name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Setup Node.js 18
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Instalar dependências do backend
      working-directory: ./backend
      run: npm install

    - name: Executar testes do backend
      working-directory: ./backend
      run: npm run test

  frontend:
    runs-on: ubuntu-latest
    needs: backend

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Instalar dependências do frontend
      working-directory: ./frontend
      run: npm install
